[package]
name = "slvy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["rustls-tls"] }
scraper = "0.20"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
anyhow = "1"
fake_user_agent = "0.2.3"
tracing = "0.1.44"
tracing-subscriber = "0.3"
async-nats = "0.42"
futures = "0.3"
bytes = "1"
sha2 = "0.11.0"
hex = "0.4.3"