import { PUBLIC_CORE_REST_URL, PUBLIC_CORE_WS_URL, PUBLIC_DISCORD_INVITE, PUBLIC_API_KEY } from '$env/static/public';

export const CORE_REST_URL = PUBLIC_CORE_REST_URL;
export const CORE_WS_URL = PUBLIC_CORE_WS_URL;
export const API_KEY = PUBLIC_API_KEY;
export const DISCORD_INVITE = PUBLIC_DISCORD_INVITE;
